CREATE TABLE users
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         varchar(254) UNIQUE NOT NULL,
    display_name  varchar(80)         NOT NULL,
    password_hash varchar(255)        NOT NULL,
    role          varchar(32)         NOT NULL,
    is_active     boolean             NOT NULL DEFAULT true,
    created_at    timestamptz         NOT NULL DEFAULT now(),
    updated_at    timestamptz         NOT NULL DEFAULT now()
);
