CREATE TABLE workspace
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id   bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT fk_workspace_owner_user FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_workspace_owner_id ON workspace (owner_id);

ALTER TABLE users
    ADD COLUMN default_workspace_id bigint NULL,
    ADD CONSTRAINT fk_user_default_workspace FOREIGN KEY (default_workspace_id) REFERENCES workspace (id) ON DELETE SET NULL;

CREATE INDEX idx_user_default_workspace_id ON users (default_workspace_id);
