CREATE TABLE envoi
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference    varchar(30)  NOT NULL,
    destinataire varchar(255) NOT NULL,
    date_envoi   date         NOT NULL DEFAULT now(),
    observation  varchar(60)  NULL,
    workspace_id bigint       NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_envoi_workspace FOREIGN KEY (id) REFERENCES workspace (id)
);

-- Because envois will almost always be fetched by workspace_id
CREATE INDEX idx_envoi_workspace_id ON envoi (workspace_id);

CREATE TABLE envoi_pieces
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    designation varchar(255) NOT NULL,
    quantite    int          NOT NULL DEFAULT 1,
    envoi_id    bigint       NOT NULL,
    CONSTRAINT fk_piece_envoi FOREIGN KEY (envoi_id) REFERENCES envoi (id)
);

CREATE INDEX idx_piece_envoi_id ON envoi_pieces (envoi_id);

