CREATE TABLE reception
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference      varchar(30)  NOT NULL,
    expediteur     varchar(255) NOT NULL,
    date_reception date         NOT NULL DEFAULT current_date,
    workspace_id   bigint       NOT NULL,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_reception_workspace FOREIGN KEY (id) REFERENCES workspace (id)
);

CREATE INDEX idx_reception_workspace ON reception (workspace_id);

CREATE TABLE reception_pieces
(
    id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    designation  varchar(255) NOT NULL,
    quantite     int          NOT NULL DEFAULT 1,
    reception_id bigint       NOT NULL,
    created_at   timestamptz  NOT NULL DEFAULT now(),
    updated_at   timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT fk_piece_reception FOREIGN KEY (reception_id) REFERENCES reception (id)
);

CREATE INDEX idx_piece_reception_id ON reception_pieces (id);
